function [X Y k hk xx yy Hx Hy w N]=domain(Npol,Ncol,rad_z,rot_z)
N{1}=Ncol;
k=(Ncol+1)/2;
[z_side z m h ang]=polygon(Npol,Ncol,rad_z,rot_z);
axis_x=real(z(1:end-1));
axis_y=imag(z(1:end-1));
xx{1}=axis_x;
yy{1}=axis_y;
for j=1:Npol-1
    x(:,j)=linspace(axis_x(j),axis_x(j+1),Ncol);
    y(:,j)=linspace(axis_y(j),axis_y(j+1),Ncol);
end
x(:,Npol)=linspace(axis_x(Npol),axis_x(1),Ncol);
y(:,Npol)=linspace(axis_y(Npol),axis_y(1),Ncol);
X{1}=reshape(x,Npol*Ncol,1);
Y{1}=reshape(y,Npol*Ncol,1);
hk=sqrt((x(1,1)-x(2,1))^2+(y(1,1)-y(2,1))^2)/tan(ang(1)-(pi/2));
w=ang-pi/2;
hx=abs(cos(w)*hk);
hy=abs(sin(w)*hk);
hx=repmat(hx',Ncol,1);
hy=repmat(hy',Ncol,1);
Hx{1}=reshape(hx,Npol*Ncol,1);
Hy{1}=reshape(hy,Npol*Ncol,1);
for i=2:k-1
    N{i}=Ncol-2*(i-1);
    Sx=-((x>0)&(y>0))+((x<0)&(y>0))+((x<0)&(y<0))-((x>0)&(y<0));
    Sy=-((x>0)&(y>0))-((x<0)&(y>0))+((x<0)&(y<0))+((x>0)&(y<0));
    Sx=Sx(2:end-1,:);
    Sy=Sy(2:end-1,:);    
    hx=hx(2:end-1,:);
    hy=hy(2:end-1,:);    
    x=x(2:end-1,:);
    y=y(2:end-1,:);
    hx=hx.*Sx;
    hy=hy.*Sy;    
    x=x+hx;
    y=y+hy;
    Hx{i}=reshape(hx,Npol*N{i},1);
    Hy{i}=reshape(hy,Npol*N{i},1);
    xx{i}=x(1,:)';
    yy{i}=y(1,:)';
    X{i}=reshape(x,size(x,1)*Npol,1);
    Y{i}=reshape(y,size(y,1)*Npol,1);
    hx=abs(hx);
    hy=abs(hy);
end